server:
  host: 127.0.0.1
  port: 8080
database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 1
  database: tool
redis:
  host: localhost
  port: 6379
  password: 1
data:
  customer: 300
  provider: 50
  group: 24
  product: 2000
  biil: 1000
  billine: 10000
  import : 1000
  importline: 10000